# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\x1a\x1bgoogle/protobuf/empty.proto\"i\n\x14\x43reateAddressRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08realname\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t\"u\n\x14UpdateAddressRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08realname\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\x04\"3\n\x14\x44\x65leteAddressRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\"/\n\x10\x41\x64\x64ressIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\"A\n\x12\x41\x64\x64ressListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0c\n\x04page\x18\x02 \x01(\r\x12\x0c\n\x04size\x18\x03 \x01(\r\"[\n\x0b\x41\x64\x64ressInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08realname\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t\"0\n\x0f\x41\x64\x64ressResponse\x12\x1d\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x0c.AddressInfo\"6\n\x13\x41\x64\x64ressListResponse\x12\x1f\n\taddresses\x18\x01 \x03(\x0b\x32\x0c.AddressInfo2\xb7\x02\n\x07\x41\x64\x64ress\x12\x38\n\rCreateAddress\x12\x15.CreateAddressRequest\x1a\x10.AddressResponse\x12>\n\rUpdateAddress\x12\x15.UpdateAddressRequest\x1a\x16.google.protobuf.Empty\x12>\n\rDeleteAddress\x12\x15.DeleteAddressRequest\x1a\x16.google.protobuf.Empty\x12\x35\n\x0eGetAddressById\x12\x11.AddressIdRequest\x1a\x10.AddressResponse\x12;\n\x0eGetAddressList\x12\x13.AddressListRequest\x1a\x14.AddressListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEADDRESSREQUEST']._serialized_start=46
  _globals['_CREATEADDRESSREQUEST']._serialized_end=151
  _globals['_UPDATEADDRESSREQUEST']._serialized_start=153
  _globals['_UPDATEADDRESSREQUEST']._serialized_end=270
  _globals['_DELETEADDRESSREQUEST']._serialized_start=272
  _globals['_DELETEADDRESSREQUEST']._serialized_end=323
  _globals['_ADDRESSIDREQUEST']._serialized_start=325
  _globals['_ADDRESSIDREQUEST']._serialized_end=372
  _globals['_ADDRESSLISTREQUEST']._serialized_start=374
  _globals['_ADDRESSLISTREQUEST']._serialized_end=439
  _globals['_ADDRESSINFO']._serialized_start=441
  _globals['_ADDRESSINFO']._serialized_end=532
  _globals['_ADDRESSRESPONSE']._serialized_start=534
  _globals['_ADDRESSRESPONSE']._serialized_end=582
  _globals['_ADDRESSLISTRESPONSE']._serialized_start=584
  _globals['_ADDRESSLISTRESPONSE']._serialized_end=638
  _globals['_ADDRESS']._serialized_start=641
  _globals['_ADDRESS']._serialized_end=952
# @@protoc_insertion_point(module_scope)
