# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x11\x43reateUserRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"(\n\x16GetUserByMobileRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"1\n\x13UpdateAvatarRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\t\"5\n\x15UpdateUsernameRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\"5\n\x15UpdatePasswordRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x12GetUserPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r\"5\n\x11VerifyUserRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x81\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06mobile\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x10\n\x08is_staff\x18\x06 \x01(\x08\x12\x12\n\nlast_login\x18\x07 \x01(\t\"+\n\x10UserInfoResponse\x12\x17\n\x04user\x18\x01 \x01(\x0b\x32\t.UserInfo\",\n\x10UserListResponse\x12\x18\n\x05users\x18\x01 \x03(\x0b\x32\t.UserInfo2\xa6\x04\n\x04User\x12\x33\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x11.UserInfoResponse\x12\x35\n\x0bGetUserById\x12\x13.GetUserByIdRequest\x1a\x11.UserInfoResponse\x12=\n\x0fGetUserByMobile\x12\x17.GetUserByMobileRequest\x1a\x11.UserInfoResponse\x12<\n\x0cUpdateAvatar\x12\x14.UpdateAvatarRequest\x1a\x16.google.protobuf.Empty\x12@\n\x0eUpdateUsername\x12\x16.UpdateUsernameRequest\x1a\x16.google.protobuf.Empty\x12@\n\x0eUpdatePassword\x12\x16.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\x12\x35\n\x0bGetUserList\x12\x13.GetUserPageRequest\x1a\x11.UserListResponse\x12\x33\n\nVerifyUser\x12\x12.VerifyUserRequest\x1a\x11.UserInfoResponse\x12\x45\n\x17GetOrCreateUserByMobile\x12\x17.GetUserByMobileRequest\x1a\x11.UserInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=43
  _globals['_CREATEUSERREQUEST']._serialized_end=78
  _globals['_GETUSERBYIDREQUEST']._serialized_start=80
  _globals['_GETUSERBYIDREQUEST']._serialized_end=112
  _globals['_GETUSERBYMOBILEREQUEST']._serialized_start=114
  _globals['_GETUSERBYMOBILEREQUEST']._serialized_end=154
  _globals['_UPDATEAVATARREQUEST']._serialized_start=156
  _globals['_UPDATEAVATARREQUEST']._serialized_end=205
  _globals['_UPDATEUSERNAMEREQUEST']._serialized_start=207
  _globals['_UPDATEUSERNAMEREQUEST']._serialized_end=260
  _globals['_UPDATEPASSWORDREQUEST']._serialized_start=262
  _globals['_UPDATEPASSWORDREQUEST']._serialized_end=315
  _globals['_GETUSERPAGEREQUEST']._serialized_start=317
  _globals['_GETUSERPAGEREQUEST']._serialized_end=365
  _globals['_VERIFYUSERREQUEST']._serialized_start=367
  _globals['_VERIFYUSERREQUEST']._serialized_end=420
  _globals['_USERINFO']._serialized_start=423
  _globals['_USERINFO']._serialized_end=552
  _globals['_USERINFORESPONSE']._serialized_start=554
  _globals['_USERINFORESPONSE']._serialized_end=597
  _globals['_USERLISTRESPONSE']._serialized_start=599
  _globals['_USERLISTRESPONSE']._serialized_end=643
  _globals['_USER']._serialized_start=646
  _globals['_USER']._serialized_end=1196
# @@protoc_insertion_point(module_scope)
